version: "3"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
  parse-platform:
    image: parseplatform/parse-server:5.2.3
    container_name: parse-platform
    ports:
      - "1337:1337"
    restart: unless-stopped
    environment:
      PARSE_SERVER_APPLICATION_ID: untendurch
      PARSE_SERVER_MASTER_KEY: untendurch
      PARSE_SERVER_DATABASE_URI: mongodb://untendurch:untendurch@mongodb:27017/untendurch
      PARSE_SERVER_MOUNT_PATH: /parse
      PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION: "false"
      PARSE_SERVER_CLOUD: /parse/cloud/main.js
      PARSE_SERVER_FILE_UPLOAD_ENABLE_FOR_PUBLIC: "true" # unfortunately this argument seems to be ignored
      PARSE_SERVER_FILE_UPLOAD_OPTIONS: '{"enableForPublic": true}'
    depends_on:
      - mongodb
    volumes:
      - parse_data:/parse-server/config
      - ./parse-server/cloud:/parse/cloud
  parse-dashboard:
    image: parseplatform/parse-dashboard:4.1.2
    container_name: parse-dashboard
    ports:
      - "4040:4040"
    restart: unless-stopped
    environment:
      PARSE_DASHBOARD_SERVER_URL: http://localhost:1337/parse
      PARSE_DASHBOARD_MASTER_KEY: untendurch
      PARSE_DASHBOARD_APP_ID: untendurch
      PARSE_DASHBOARD_APP_NAME: untendurch
      PARSE_DASHBOARD_USER_ID: untendurch
      PARSE_DASHBOARD_USER_PASSWORD: untendurch
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: "true"
      PARSE_DASHBOARD_GRAPHQL_SERVER_URL: http://localhost:1337/graphql
  mongodb:
    image: mongo:5.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: untendurch
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_USERNAME: untendurch
      MONGO_INITDB_PASSWORD: untendurch
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
