  services:
    reverse-proxy:
      restart: always
      image: caddy:2
      volumes:
        - ./caddy/Caddyfile:/etc/caddy/Caddyfile
        - ./caddy/data:/data
      ports:
        - "80:80"
        - "443:443/tcp"
        - "443:443/udp"
      networks:
        default:
          aliases:
            - internal
            - external

    app:
      image: tegonal/untendurch:${IMAGE_VERSION}
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "curl http://localhost:${PARSE_SERVER_PORT}/ || exit 1"]
        interval: 10s
        retries: 5
        start_period: 5s
        timeout: 10s
      depends_on:
        mongodb:
          condition: service_healthy
      env_file: .env
      volumes:
        - parse_uploads:/app/packages/backend/files
      networks:
        default:
          aliases:
            - internal

    mongodb:
      image: mongo:7.0.8
      container_name: mongodb
      ports:
        - "27017:27017"
      restart: unless-stopped
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_INITDB_DATABASE} --quiet
      env_file: .env
      volumes:
        - mongodb_data:/data/db
        - ./mongodb/dumps:/dumps
        - ./mongodb/mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
      networks:
        default:
          aliases:
            - internal

    mongodb-backup:
      image: ghcr.io/tiredofit/docker-db-backup
      env_file: .env
      restart: always
      depends_on:
        mongodb:
          condition: service_healthy
      networks:
        default:
          aliases:
            - internal

    volume-backup:
      image: offen/docker-volume-backup:v2
      env_file: .env
      volumes:
        - parse_uploads:/backup/parse_uploads:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        default:
          aliases:
            - internal

  volumes:
    mongodb_data:
      driver: local
    parse_uploads:
      driver: local

  networks:
    default:
      name: external
      external: true
