name: Build and publish docker images

on: 
  push:
    tags:
      - '**'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: tegonal/untendurch-frontend:${{github.ref_name}}
          build-args: "ENVIRONMENT=test"
      - name: Build and push custom Parse-Server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/parse-server/Dockerfile
          push: true
          tags: tegonal/untendurch-parse-server:${{github.ref_name}}
